import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const bancosData = [
  {
    cod_febraban: 246,
    nome: 'Banco ABC Brasil S.A.',
    chave: 'BANCO_ABC_BRASIL_S_A',
    site: 'www.abcbrasil.com.br',
  },
  {
    cod_febraban: 299,
    nome: 'Banco Afinz S.A. Banco Múltiplo',
    chave: 'BANCO_AFINZ_S_A_BANCO_MULTIPLO',
    site: 'afinz.com.br',
  },
  {
    cod_febraban: 121,
    nome: 'Banco Agibank S.A.',
    chave: 'BANCO_AGIBANK_S_A',
    site: 'www.agibank.com.br',
  },
  {
    cod_febraban: 65,
    nome: 'Banco Andbank (Brasil) S.A.',
    chave: 'BANCO_ANDBANK_BRASIL_S_A',
    site: 'www.andbank-lla.com.br',
  },
  {
    cod_febraban: 96,
    nome: 'Banco B3 S.A.',
    chave: 'BANCO_B3_S_A',
    site: 'www.bmfbovespa.com.br/bancobmfbovespa/',
  },
  {
    cod_febraban: 24,
    nome: 'Banco BANDEPE S.A.',
    chave: 'BANCO_BANDEPE_S_A',
    site: 'www.santander.com.br',
  },
  {
    cod_febraban: 318,
    nome: 'Banco BMG S.A.',
    chave: 'BANCO_BMG_S_A',
    site: 'www.bancobmg.com.br',
  },
  {
    cod_febraban: 752,
    nome: 'Banco BNP Paribas Brasil S.A.',
    chave: 'BANCO_BNP_PARIBAS_BRASIL_S_A',
    site: 'www.bnpparibas.com.br',
  },
  {
    cod_febraban: 107,
    nome: 'Banco BOCOM BBM S.A.',
    chave: 'BANCO_BOCOM_BBM_S_A',
    site: 'www.bancobbm.com.br',
  },
  {
    cod_febraban: 63,
    nome: 'Banco Bradescard S.A.',
    chave: 'BANCO_BRADESCARD_S_A',
    site: 'www.ibi.com.br',
  },
  {
    cod_febraban: 36,
    nome: 'Banco Bradesco BBI S.A.',
    chave: 'BANCO_BRADESCO_BBI_S_A',
    site: null,
  },
  {
    cod_febraban: 394,
    nome: 'Banco Bradesco Financiamentos S.A.',
    chave: 'BANCO_BRADESCO_FINANCIAMENTOS_S_A',
    site: null,
  },
  {
    cod_febraban: 237,
    nome: 'Banco Bradesco S.A.',
    chave: 'BANCO_BRADESCO_S_A',
    site: 'www.bradesco.com.br',
  },
  {
    cod_febraban: 218,
    nome: 'Banco BS2 S.A.',
    chave: 'BANCO_BS2_S_A',
    site: 'www.bs2.com/banco/',
  },
  {
    cod_febraban: 208,
    nome: 'Banco BTG Pactual S.A.',
    chave: 'BANCO_BTG_PACTUAL_S_A',
    site: 'www.btgpactual.com',
  },
  {
    cod_febraban: 626,
    nome: 'Banco C6 Consignado S.A.',
    chave: 'BANCO_C6_CONSIGNADO_S_A',
    site: 'https://www.c6consig.com.br/',
  },
  {
    cod_febraban: null,
    nome: 'Banco C6 S.A.',
    chave: 'BANCO_C6_S_A',
    site: 'https://www.c6bank.com/',
  },
  {
    cod_febraban: 473,
    nome: 'Banco Caixa Geral - Brasil S.A.',
    chave: 'BANCO_CAIXA_GERAL_BRASIL_S_A',
    site: 'www.bcgbrasil.com.br',
  },
  {
    cod_febraban: 40,
    nome: 'Banco Cargill S.A.',
    chave: 'BANCO_CARGILL_S_A',
    site: 'www.bancocargill.com.br',
  },
  {
    cod_febraban: 233,
    nome: 'Banco Cifra S.A.',
    chave: 'BANCO_CIFRA_S_A',
    site: 'www.bancocifra.com.br',
  },
  {
    cod_febraban: 745,
    nome: 'Banco Citibank S.A.',
    chave: 'BANCO_CITIBANK_S_A',
    site: 'www.citibank.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco CNH Industrial Capital S.A.',
    chave: 'BANCO_CNH_INDUSTRIAL_CAPITAL_S_A',
    site: 'www.cnhindustrialcapital.com',
  },
  {
    cod_febraban: 756,
    nome: 'Banco Cooperativo Sicoob S.A.',
    chave: 'BANCO_COOPERATIVO_SICOOB_S_A',
    site: 'www.Sicoob.com.br',
  },
  {
    cod_febraban: 748,
    nome: 'Banco Cooperativo Sicredi S.A.',
    chave: 'BANCO_COOPERATIVO_SICREDI_S_A',
    site: 'www.sicredi.com.br',
  },
  {
    cod_febraban: 222,
    nome: 'Banco Credit Agricole Brasil S.A.',
    chave: 'BANCO_CREDIT_AGRICOLE_BRASIL_S_A',
    site: 'www.calyon.com.br',
  },
  {
    cod_febraban: 505,
    nome: 'Banco Credit Suisse (Brasil) S.A.',
    chave: 'BANCO_CREDIT_SUISSE_BRASIL_S_A',
    site: 'www.csfb.com',
  },
  {
    cod_febraban: null,
    nome: 'Banco CSF S.A.',
    chave: 'BANCO_CSF_S_A',
    site: null,
  },
  {
    cod_febraban: 3,
    nome: 'Banco da Amazônia S.A.',
    chave: 'BANCO_DA_AMAZONIA_S_A',
    site: 'www.bancoamazonia.com.br',
  },
  {
    cod_febraban: 83,
    nome: 'Banco da China Brasil S.A.',
    chave: 'BANCO_DA_CHINA_BRASIL_S_A',
    site: 'www.boc-brazil.com',
  },
  {
    cod_febraban: 707,
    nome: 'Banco Daycoval S.A.',
    chave: 'BANCO_DAYCOVAL_S_A',
    site: 'www.daycoval.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco de Lage Landen Brasil S.A.',
    chave: 'BANCO_DE_LAGE_LANDEN_BRASIL_S_A',
    site: 'www.dllgroup.com',
  },
  {
    cod_febraban: 654,
    nome: 'Banco Digimais S.A.',
    chave: 'BANCO_DIGIMAIS_S_A',
    site: 'www.bancodigimais.com.br/',
  },
  {
    cod_febraban: null,
    nome: 'Banco Digio S.A.',
    chave: 'BANCO_DIGIO_S_A',
    site: 'www.aebb.com.br',
  },
  {
    cod_febraban: 1,
    nome: 'Banco do Brasil S.A.',
    chave: 'BANCO_DO_BRASIL_S_A',
    site: 'www.bb.com.br',
  },
  {
    cod_febraban: 47,
    nome: 'Banco do Estado de Sergipe S.A.',
    chave: 'BANCO_DO_ESTADO_DE_SERGIPE_S_A',
    site: 'www.banese.com.br',
  },
  {
    cod_febraban: 37,
    nome: 'Banco do Estado do Pará S.A.',
    chave: 'BANCO_DO_ESTADO_DO_PARA_S_A',
    site: 'www.banpara.b.br',
  },
  {
    cod_febraban: 41,
    nome: 'Banco do Estado do Rio Grande do Sul S.A.',
    chave: 'BANCO_DO_ESTADO_DO_RIO_GRANDE_DO_SUL_S_A',
    site: 'www.banrisul.com.br',
  },
  {
    cod_febraban: 4,
    nome: 'Banco do Nordeste do Brasil S.A.',
    chave: 'BANCO_DO_NORDESTE_DO_BRASIL_S_A',
    site: 'www.banconordeste.gov.br',
  },
  {
    cod_febraban: 224,
    nome: 'Banco Fibra S.A.',
    chave: 'BANCO_FIBRA_S_A',
    site: 'www.bancofibra.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco Fidis S.A.',
    chave: 'BANCO_FIDIS_S_A',
    site: 'www.bancofidis.com.br',
  },
  {
    cod_febraban: 94,
    nome: 'Banco Finaxis S.A.',
    chave: 'BANCO_FINAXIS_S_A',
    site: 'www.bancofinaxis.com.br',
  },
  {
    cod_febraban: 125,
    nome: 'Banco Genial S.A.',
    chave: 'BANCO_GENIAL_S_A',
    site: 'www.bancogenial.com',
  },
  {
    cod_febraban: null,
    nome: 'Banco GM S.A.',
    chave: 'BANCO_GM_S_A',
    site: 'www.chevroletsf.com.br',
  },
  {
    cod_febraban: 612,
    nome: 'Banco Guanabara S.A.',
    chave: 'BANCO_GUANABARA_S_A',
    site: 'www.bancoguanabara.com.br',
  },
  {
    cod_febraban: 269,
    nome: 'Banco HSBC S.A.',
    chave: 'BANCO_HSBC_S_A',
    site: null,
  },
  {
    cod_febraban: null,
    nome: 'Banco IBM S.A.',
    chave: 'BANCO_IBM_S_A',
    site: 'www.ibm.com/financing/br',
  },
  {
    cod_febraban: 12,
    nome: 'Banco Inbursa S.A.',
    chave: 'BANCO_INBURSA_S_A',
    site: 'www.bancoinbursa.com',
  },
  {
    cod_febraban: 604,
    nome: 'Banco Industrial do Brasil S.A.',
    chave: 'BANCO_INDUSTRIAL_DO_BRASIL_S_A',
    site: 'www.bancoindustrial.com.br',
  },
  {
    cod_febraban: 77,
    nome: 'Banco Inter S.A.',
    chave: 'BANCO_INTER_S_A',
    site: 'www.bancointer.com.br',
  },
  {
    cod_febraban: 249,
    nome: 'Banco Investcred Unibanco S.A.',
    chave: 'BANCO_INVESTCRED_UNIBANCO_S_A',
    site: null,
  },
  {
    cod_febraban: 184,
    nome: 'Banco Itaú BBA S.A.',
    chave: 'BANCO_ITAU_BBA_S_A',
    site: 'www.itaubba.com.br',
  },
  {
    cod_febraban: 29,
    nome: 'Banco Itaú Consignado S.A.',
    chave: 'BANCO_ITAU_CONSIGNADO_S_A',
    site: null,
  },
  {
    cod_febraban: null,
    nome: 'Banco Itaú Veículos S.A.',
    chave: 'BANCO_ITAU_VEICULOS_S_A',
    site: 'www.bancofiat.com.br',
  },
  {
    cod_febraban: 479,
    nome: 'Banco ItauBank S.A',
    chave: 'BANCO_ITÁUBANK_S_A',
    site: 'www.itaubank.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco Itaucard S.A.',
    chave: 'BANCO_ITAU_CARD_S_A',
    site: 'www.itau.com.br',
  },
  {
    cod_febraban: 376,
    nome: 'Banco J. P. Morgan S.A.',
    chave: 'BANCO_J_P_MORGAN_S_A',
    site: 'www.jpmorgan.com',
  },
  {
    cod_febraban: 74,
    nome: 'Banco J. Safra S.A.',
    chave: 'BANCO_J_SAFRA_S_A',
    site: 'www.safra.com.br',
  },
  {
    cod_febraban: 217,
    nome: 'Banco John Deere S.A.',
    chave: 'BANCO_JOHN_DEERE_S_A',
    site: 'www.johndeere.com.br',
  },
  {
    cod_febraban: 630,
    nome: 'Banco Letsbank S.A.',
    chave: 'BANCO_LETSBANK_S_A',
    site: 'www.letsbank.com.br',
  },
  {
    cod_febraban: 600,
    nome: 'Banco Luso Brasileiro S.A.',
    chave: 'BANCO_LUSO_BRASILEIRO_S_A',
    site: 'www.lusobrasileiro.com.br',
  },
  {
    cod_febraban: 243,
    nome: 'Banco Master S.A.',
    chave: 'BANCO_MASTER_S_A',
    site: 'www.bancomaster.com.br',
  },
  {
    cod_febraban: 389,
    nome: 'Banco Mercantil do Brasil S.A.',
    chave: 'BANCO_MERCANTIL_DO_BRASIL_S_A',
    site: 'www.mercantil.com.br',
  },
  {
    cod_febraban: 370,
    nome: 'Banco Mizuho do Brasil S.A.',
    chave: 'BANCO_MIZUHO_DO_BRASIL_S_A',
    site: 'www.mizuhobank.com/brazil/pt/',
  },
  {
    cod_febraban: 746,
    nome: 'Banco Modal S.A.',
    chave: 'BANCO_MODAL_S_A',
    site: 'www.bancomodal.com.br',
  },
  {
    cod_febraban: 66,
    nome: 'Banco Morgan Stanley S.A.',
    chave: 'BANCO_MORGAN_STANLEY_S_A',
    site: null,
  },
  {
    cod_febraban: 456,
    nome: 'Banco MUFG Brasil S.A.',
    chave: 'BANCO_MUFG_BRASIL_S_A',
    site: 'www.br.bk.mufg.jp',
  },
  {
    cod_febraban: 7,
    nome: 'Banco Nacional de Desenvolvimento Econômico e Social - BNDES',
    chave: 'BANCO_NACIONAL_DE_DESENVOLVIMENTO_ECONOMICO_E_SOCIAL_BNDES',
    site: 'www.bndes.gov.br',
  },
  {
    cod_febraban: 212,
    nome: 'Banco Original S.A.',
    chave: 'BANCO_ORIGINAL_S_A',
    site: 'www.original.com.br',
  },
  {
    cod_febraban: 712,
    nome: 'Banco Ourinvest S.A.',
    chave: 'BANCO_OURINVEST_S_A',
    site: 'www.ourinvest.com.br',
  },
  {
    cod_febraban: 623,
    nome: 'Banco PAN S.A.',
    chave: 'BANCO_PAN_S_A',
    site: 'www.bancopan.com.br',
  },
  {
    cod_febraban: 611,
    nome: 'Banco Paulista S.A.',
    chave: 'BANCO_PAULISTA_S_A',
    site: 'www.bancopaulista.com.br',
  },
  {
    cod_febraban: 643,
    nome: 'Banco Pine S.A.',
    chave: 'BANCO_PINE_S_A',
    site: 'www.pine.com',
  },
  {
    cod_febraban: 747,
    nome: 'Banco Rabobank International Brasil S.A.',
    chave: 'BANCO_RABOBANK_INTERNATIONAL_BRASIL_S_A',
    site: 'www.rabobank.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco RCI Brasil S.A.',
    chave: 'BANCO_RCI_BRASIL_S_A',
    site: 'www.bancorenault.com.br',
  },
  {
    cod_febraban: 633,
    nome: 'Banco Rendimento S.A.',
    chave: 'BANCO_RENDIMENTO_S_A',
    site: 'www.rendimento.com.br',
  },
  {
    cod_febraban: 120,
    nome: 'Banco Rodobens S.A.',
    chave: 'BANCO_RODOBENS_S_A',
    site: 'www.rodobens.com.br',
  },
  {
    cod_febraban: 422,
    nome: 'Banco Safra S.A.',
    chave: 'BANCO_SAFRA_S_A',
    site: 'www.safra.com.br',
  },
  {
    cod_febraban: 33,
    nome: 'Banco Santander  (Brasil)  S.A.',
    chave: 'BANCO_SANTANDER_BRASIL_S_A',
    site: 'www.santander.com.br',
  },
  {
    cod_febraban: 743,
    nome: 'Banco Semear S.A.',
    chave: 'BANCO_SEMEAR_S_A',
    site: 'www.bancosemear.com.br',
  },
  {
    cod_febraban: 276,
    nome: 'Banco Senff S.A.',
    chave: 'BANCO_SENFF_S_A',
    site: 'https://www.senff.com.br/',
  },
  {
    cod_febraban: 366,
    nome: 'Banco Société Générale Brasil S.A.',
    chave: 'BANCO_SOCITE_GÉNÉRALE_BRASIL_S_A',
    site: 'www.sgbrasil.com.br',
  },
  {
    cod_febraban: 464,
    nome: 'Banco Sumitomo Mitsui Brasileiro S.A.',
    chave: 'BANCO_SUMITOMO_MITSUI_BRASILEIRO_S_A',
    site: 'www.smbcgroup.com.br',
  },
  {
    cod_febraban: 82,
    nome: 'Banco Topázio S.A.',
    chave: 'BANCO_TOPÁZIO_S_A',
    site: 'www.bancotopazio.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco Toyota do Brasil S.A.',
    chave: 'BANCO_TOYOTA_DO_BRASIL_S_A',
    site: 'www.bancotoyota.com.br',
  },
  {
    cod_febraban: 634,
    nome: 'Banco Triângulo S.A.',
    chave: 'BANCO_TRIÂNGULO_S_A',
    site: 'www.tribanco.com.br',
  },
  {
    cod_febraban: 653,
    nome: 'Banco Voiter S.A.',
    chave: 'BANCO_VOITER_S_A',
    site: 'www.voiter.com',
  },
  {
    cod_febraban: null,
    nome: 'Banco Volkswagen S.A.',
    chave: 'BANCO_VOLKSWAGEN_S_A',
    site: 'www.bancovw.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Banco Volvo Brasil S.A.',
    chave: 'BANCO_VOLVO_BRASIL_S_A',
    site: null,
  },
  {
    cod_febraban: 655,
    nome: 'Banco Votorantim S.A.',
    chave: 'BANCO_VOTORANTIM_S_A',
    site: 'www.bancovotorantim.com.br',
  },
  {
    cod_febraban: 610,
    nome: 'Banco VR S.A.',
    chave: 'BANCO_VR_S_A',
    site: 'www.vrinvestimentos.com.br',
  },
  {
    cod_febraban: 119,
    nome: 'Banco Western Union do Brasil S.A.',
    chave: 'BANCO_WESTERN_UNION_DO_BRASIL_S_A',
    site: 'www.bancowesternunion.com.br',
  },
  {
    cod_febraban: 348,
    nome: 'Banco XP S.A.',
    chave: 'BANCO_XP_S_A',
    site: null,
  },
  {
    cod_febraban: null,
    nome: 'Banco Yamaha Motor do Brasil S.A.',
    chave: 'BANCO_YAMAHA_MOTOR_DO_BRASIL_S_A',
    site: 'www.yamaha-motor.com.br',
  },
  {
    cod_febraban: 21,
    nome: 'BANESTES S.A. Banco do Estado do Espírito Santo',
    chave: 'BANESTES_S_A_BANCO_DO_ESTADO_DO_ESPÍRITO_SANTO',
    site: 'www.banestes.com.br',
  },
  {
    cod_febraban: 755,
    nome: 'Bank of America Merrill Lynch Banco Múltiplo S.A.',
    chave: 'BANK_OF_AMERICA_MERRILL_LYNCH_BANCO_MULTIPLO_S_A',
    site: 'www.ml.com',
  },
  {
    cod_febraban: 250,
    nome: 'BCV - Banco de Crédito e Varejo S.A.',
    chave: 'BCV_BANCO_DE_CREDITO_E_VAREJO_S_A',
    site: 'www.bancobcv.com.br',
  },
  {
    cod_febraban: 128,
    nome: 'Braza Bank S.A. Banco de Câmbio',
    chave: 'BRAZA_BANK_S_A_BANCO_DE_CAMBIO',
    site: 'www.msbank.com.br',
  },
  {
    cod_febraban: 70,
    nome: 'BRB - Banco de Brasília S.A.',
    chave: 'BRB_BANCO_DE_BRASILIA_S_A',
    site: 'www.brb.com.br',
  },
  {
    cod_febraban: 104,
    nome: 'Caixa Econômica Federal',
    chave: 'CAIXA_ECONOMICA_FEDERAL',
    site: 'www.caixa.gov.br',
  },
  {
    cod_febraban: 320,
    nome: 'China Construction Bank (Brasil) Banco Múltiplo S.A.',
    chave: 'CHINA_CONSTRUCTION_BANK_BRASIL_BANCO_MULTIPLO_S_A',
    site: 'www.br.ccb.com',
  },
  {
    cod_febraban: 477,
    nome: 'Citibank N.A.',
    chave: 'CITIBANK_N_A',
    site: 'www.citibank.com',
  },
  {
    cod_febraban: 487,
    nome: 'Deutsche Bank S.A. - Banco Alemão',
    chave: 'DEUTSCHE_BANK_S_A_BANCO_ALEMAO',
    site: 'www.deutsche-bank.com.br',
  },
  {
    cod_febraban: 144,
    nome: 'Ebury Banco de Câmbio S.A.',
    chave: 'EBURY_BANCO_DE_CAMBIO_S_A',
    site: 'www.bexs.com.br',
  },
  {
    cod_febraban: 62,
    nome: 'Hipercard Banco Múltiplo S.A.',
    chave: 'HIPERCARD_BANCO_MULTIPLO_S_A',
    site: 'www.hipercard.com.br',
  },
  {
    cod_febraban: 341,
    nome: 'Itaú Unibanco S.A.',
    chave: 'ITAU_UNIBANCO_S_A',
    site: 'www.itau.com.br',
  },
  {
    cod_febraban: 488,
    nome: 'JPMorgan Chase Bank, National Association',
    chave: 'JPMORGAN_CHASE_BANK_NATIONAL_ASSOCIATION',
    site: 'www.jpmorganchase.com',
  },
  {
    cod_febraban: 399,
    nome: 'Kirton Bank S.A. - Banco Múltiplo',
    chave: 'KIRTON_BANK_S_A_BANCO_MULTIPLO',
    site: null,
  },
  {
    cod_febraban: 254,
    nome: 'Paraná Banco S.A.',
    chave: 'PARANÁ_BANCO_S_A',
    site: 'www.paranabanco.com.br',
  },
  {
    cod_febraban: null,
    nome: 'Scania Banco S.A.',
    chave: 'SCANIA_BANCO_S_A',
    site: 'www.scaniabanco.com.br',
  },
  {
    cod_febraban: 751,
    nome: 'Scotiabank Brasil S.A. Banco Múltiplo',
    chave: 'SCOTIABANK_BRASIL_S_A_BANCO_MULTIPLO',
    site: 'www.br.scotiabank.com',
  },
  {
    cod_febraban: 14,
    nome: 'State Street Brasil S.A. - Banco Comercial',
    chave: 'STATE_STREET_BRASIL_S_A_BANCO_COMERCIAL',
    site: 'www.statestreet.com',
  },
  {
    cod_febraban: 95,
    nome: 'Travelex Banco de Câmbio S.A.',
    chave: 'TRAVELEX_BANCO_DE_CAMBIO_S_A',
    site: 'www.bancoconfidence.com.br',
  },
  {
    cod_febraban: 129,
    nome: 'UBS Brasil Banco de Investimento S.A.',
    chave: 'UBS_BRASIL_BANCO_DE_INVESTIMENTO_S_A',
    site: 'www.ubs.com',
  },
];

async function main() {
  for (const banco of bancosData) {
    await prisma.bancos.create({
      data: banco,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('Bancos inseridos com sucesso!');
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
